#!/bin/bash
################################################################################
#                                                                              #
#  Copyright (C) 2007, 2019 David Both                                         #
#  LinuxGeek46@both.org                                                        #
#                                                                              #
#  This program is free software; you can redistribute it and/or modify        #
#  it under the terms of the GNU General Public License as published by        #
#  the Free Software Foundation; either version 2 of the License, or           #
#  (at your option) any later version.                                         #
#                                                                              #
#  This program is distributed in the hope that it will be useful,             #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of              #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
#  GNU General Public License for more details.                                #
#                                                                              #
#  You should have received a copy of the GNU General Public License           #
#  along with this program; if not, write to the Free Software                 #
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA   #
#                                                                              #
################################################################################
################################################################################
################################################################################

################################################################################
# Functions                                                                    #
################################################################################
Help()
{
   # Display Help
   echo "Connecting to a remote host using SSH."
   echo
   echo "Syntax: ssh [-p|h|t|V]"
   echo "options:"
   echo "p     Connect using 2220 port."
   echo "h     Print this Help."
   echo "V     Print software version and exit."
   echo
}

connect(){
   # Connect to the remote host
   ssh -p $PORT $USER@$HOST
}
################################################################################
# Set variables                                                                #
################################################################################
PORT=2220
USER="bandit0"
HOST="bandit.labs.overthewire.org"
################################################################################
################################################################################
# Main program                                                                 #
################################################################################
################################################################################
# Get the options
while getopts ":hp:vu:l:d" option; do
   case $option in
      h) # display Help
         Help
         exit;;
     \?) # incorrect option
         echo "Error: Invalid option"
         exit;;
      V) # display version
         echo "ssh version 0.1"
         exit;;
      p) # connect using port 2220
         PORT="$OPTARG"
         run=1
         ;;
      u) # connect using port 2220
         USER="$OPTARG"
         run=1
         ;;
      l) # connect using port 2220
         HOST="$OPTARG"
         run=1
         ;;
      d) # connect using port 2220
         echo "Default mode"
         run=1
         ;;
   esac
done

echo $run
if [ $run = 1 ]; then
      echo "Connecting to $USER@$HOST using port $PORT"
      connect
fi
