#! /bin/bash

###################
#
#   aceron
#   Junio 13, 2023
#
###################

#### Global

#### Funciones
Create(){
    createFile
    if [ $? -eq 0 ]; then
        echo File ${NAME} succesfully created
    else
        echo Error: Cannot created ${!NAME}
        return $?
    fi
}

createFile(){
    echo -e "---
layout: post
title: \"La expanción de Querétaro vs los parques públicos\"
description: \"A work at home parent is an entrepreneur who works from home and integrates parenting into his or her business activities.\"
date: 2023-01-06
feature_image: images/blogs/misc/p1-qro-trash.jpeg
tags: [miscelanea, opiniones]
---
    proximamente...
    <!--more-->
" > someName.md
}

Delete(){
    echo "Delete functuib"
}

help(){
    echo "Help functio"
}

### Variables

# Lógica del programa
case $1 in
    create )
        Create ;; 

    * )
        help ;;
esac