#! /bin/bash

###################
#
#   aceron
#   Junio 13, 2023
#
###################

#### Global
NAME="defaulName"
LAYOUT="defaulBlogLayout"
TITLE="defaulBlogTitle"
DESCRIPTION="defaultBlogDescription"
DATE=YYY-MM-DD
BACKGROUND="ptah\to\image.png"
LABELS="default, labels, to, blog"

#### Funciones
Create(){
    createFile
    if [ $? -eq 0 ]; then
        echo File ${NAME} succesfully created
    else
        echo Error: Cannot created ${NAME}
        return $?
    fi
}

createFile(){
    echo -e "---
layout: ${LAYOUT}
title: \"${TITLE}\"
description: \"${DESCRIPTION}.\"
date: ${DATE}
feature_image: ${BACKGROUND}
tags: [${LABELS}]
---
    proximamente...
    <!--more-->
" > ./${NAME}.md
}

Delete(){
    echo "Delete functuion"
}

help(){
    echo "Help functio"
}

### Variables

# Lógica del programa
POSITIONAL_ARGS=( )
case $1 in
    create )
        for i in "$@"; do
            case $i in 
                -n|--name)
                    NAME=$2
                    shift
                    shift
                    ;;
                -L|--layout)
                    LAYOUT=$2
                    shift
                    shift
                    ;;
                -D|--description)
                    DESCRIPTION=$2
                    shift
                    shift
                    ;;
                -d|--date)
                    DATE=$2
                    shift
                    shift
                    ;;
                -bg|--background)
                    BACKGROUND=$2
                    shift
                    shift
                    ;;
                -l|--labels)
                    LABELS=$2
                    shift
                    shift
                    ;;
                -*|--*)
                    echo "Unknown option $1"
                    exit 1
                    ;;
                *)
                    POSITIONAL_ARGS+=("$1") # save positional arg
                    shift # past argument
                    ;;
            esac
        done 
        Create ;; 

    * )
        help ;;
esac



##Notes

#bsahesqual
#-n=*|--name=*